### http-sample -- without url path --
GET {{host}}

### http-sample -- with url path --
GET {{host}}/Alfred

### part2
GET {{host}}/view/NameToLoadAndDisplay

### part3 -- display the file == part2 --
GET {{host}}/view/NameToLoadAndDisplay

### part3 -- form to adjust the file --
GET {{host}}/edit/NameToLoadAndDisplay